### ISSUE TITLE
[BUG] - Can't configure private_link_access

### ISSUE THREAD

**Issue by cveld** [CloudNationHQ/terraform-azure-sa#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Module Version

3.0.2

### Terraform Version

1.9.8

### AzureRM Provider Version

4.3

### Short Description

Can't configure private_link_access

### Terraform Configuration Files

```
...
network_rules = {
      default_action = "Deny"
      private_link_access = {
        endpoint_resource_id = "/subscriptions/${local.subscription_id}/providers/Microsoft.Security/datascanners/storageDataScanner"
        endpoint_tenant_id   = "redacted"
      }
    }
...
```

### Expected Behaviour

It should just work

### Actual Behaviour

As the for_each expression is not correct, it starts looping across the wrong key/value pairs:

```
 Error: Unsupported attribute
│
│   on .terraform\modules\storage\main.tf line 43, in resource "azurerm_storage_account" "sa":
│   43:           endpoint_resource_id = private_link_access.value.endpoint_resource_id
│     ├────────────────
│     │ private_link_access.value is "/subscriptions/redacted/providers/Microsoft.Security/datascanners/storageDataScanner"
│
│ Can't access attributes on a primitive-typed value (string).
```

### Steps to Reproduce

`terraform apply`

### Additional Context

`for_each = { for key, pla in try(var.storage.network_rules.private_link_access, {}) : key => pla }`

should be replaced by

`for_each = try(var.storage.network_rules.private_link_access, null) != null ? [var.storage.network_rules.private_link_access] : []`

**Comment by eddy-vera** [comment]
As discussed, it works as intended, an additional key was required as multiple private_link_access blocks can be defined, e.g. `data_scanner` :
```
private_link_access = {
          data_scanner = {
            endpoint_resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/providers/Microsoft.Security/datascanners/StorageDataScanner"
            endpoint_tenant_id   = data.azurerm_client_config.current.tenant_id
          }
        }
```
