### ISSUE TITLE
[REQUEST] - Update version of Random provider to ~> 3.6

### ISSUE THREAD

**Issue by eddy-vera** [CloudNationHQ/terraform-azure-sa#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Random version provider is currently set to ~> 3.5.1 and using this module in conjunction with the CAF Enterprise Scale module (latest 6.0.0 version) I have encountered a constraint error due to incompatible provider version specifications. The error message received is as follows:

```
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/random: no available releases match the given constraints ~>
│ 3.5.1, ~> 3.6
```

To resolve this issue and allow for minor updates, the request is for the module's dependency constraint to be updated from ~> 3.5.1 to ~> 3.6. This change will ensure compatibility with other modules and prevent version conflicts.

### Potential Terraform Configuration

```
random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
```

**Comment by dkooll** [comment]
solved in #84
